//@version=5

strategy(title='Net Momentum & Expansion & Weekly Breakout Strategy', overlay=true, pyramiding = 10, calc_on_every_tick = true)
condition = input.source(open, "Ex")
tpsltype = input.string('ATR', 'Type of TP&SL', ['Pivot', 'ATR'], group = 'Setting TP&SL')
ATRMultiple = input.float(1, 'ATR Multiple', 1, 3, 0.5, group = 'Setting TP&SL')
ATRPeriod = input.int(14, 'ATR Period', group = 'Setting TP&SL')
HistoryBarCount = input.int(1000, title = 'Bar Count for Calculate Pivot Point')

buySignal = false
sellSignal = false

if condition == 1
    buySignal := true
if condition == -1
    sellSignal := true

tp=0.0
sl=0.0

atr = ta.atr(ATRPeriod)*ATRMultiple

if tpsltype == 'ATR'	
	tp := buySignal ? close+atr : sellSignal ? close-atr : tp[1] 
	sl := buySignal ? close-atr : sellSignal ? close+atr : sl[1]	

else if tpsltype == 'Pivot' and buySignal
	tmpTp = high//buySignal ? high : sellSignal ? low : tmpTp[1]
	tmpSl = low
	i = 1
	barIndex = bar_index
	while barIndex > bar_index - HistoryBarCount
		if high[i] > tmpTp and high[i] > high[i+1]
			tmpTp := high[i]
			break
		i += 1
		barIndex -= 1
	if tmpTp == high 		
		tp := high+atr
	else
		tp := tmpTp

	i := 1
	barIndex := bar_index
	while barIndex > bar_index - HistoryBarCount
		if low[i] < tmpSl and low[i] < low[i+1]
			tmpSl := low[i]
			break
		i += 1
		barIndex -= 1
	if tmpSl == low 		
		sl := low-atr
	else
		sl := tmpSl

else if tpsltype == 'Pivot' and sellSignal
	tmpSl = high
	tmpTp = low
	i = 1
	barIndex = bar_index
	while barIndex > bar_index - HistoryBarCount
		if high[i] > tmpSl and high[i] > high[i+1]
			tmpSl := high[i]
			break
		i += 1
		barIndex -= 1
	if tmpSl == high 		
		sl := high+atr
	else
		sl := tmpSl

	i := 1
	barIndex := bar_index
	while barIndex > bar_index - HistoryBarCount
		if low[i] < tmpTp and low[i] < low[i+1]
			tmpTp := low[i]
			break
		i += 1
		barIndex -= 1
	if tmpTp == low 		
		tp := low-atr
	else
		tp := tmpTp

else if tpsltype == 'Pivot' and not buySignal and not sellSignal
	tp := tp[1]
	sl := sl[1]

plot(tp, color=color.green, style = plot.style_circles)
plot(sl, color=color.red, style = plot.style_circles)

var testTable = table.new(position = position.top_right, columns = 2, rows = 1, bgcolor = color.lime, border_width = 1)

if barstate.islast
    table.cell(table_id = testTable, column = 0, row = 0, text = "TP: " + str.tostring(tp), bgcolor = color.green)
    table.cell(table_id = testTable, column = 1, row = 0, text = "SL:  " + str.tostring(sl), bgcolor = color.red)

if buySignal
	id = "buy"+str.tostring(bar_index)
	strategy.entry(id, strategy.long)
	strategy.exit("buyexit", id, profit = (tp-close)/syminfo.mintick, loss = (close-sl)/syminfo.mintick, comment_profit=id+"TP", comment_loss=id+"SL")
if sellSignal
	id = "sell"+str.tostring(bar_index)
	strategy.entry(id, strategy.short)
	strategy.exit("sellexit",id, profit = (close-tp)/syminfo.mintick, loss = (sl-close)/syminfo.mintick, comment_profit=id+"TP", comment_loss=id+"SL")